# -*- coding: utf-8 -*-
# Widen the blue "AI Assistant" pill in the English CorpID header images
# (the pill generated by _make_en_headers.py is too snug for the English text).
# Strategy: work on a 4x-supersampled crop, repaint the white search-pill shape
# (erases the old blue pill without touching the sky outside the pill),
# draw a wider blue rounded pill, re-render the text centered, paste back.
from PIL import Image, ImageDraw, ImageFont

BASE = r"C:/Projects/CorpID/Mock-HTML/Mobile/IAM_To_CorpID/images"
ARIAL_BD = r"C:/Windows/Fonts/arialbd.ttf"
S = 4  # supersampling factor

def median_blue(img):
    # sample interior of the old blue pill, away from its white text
    bp = []
    for y in range(845, 865):
        for x in range(950, 1100):
            r, g, b = img.getpixel((x, y))[:3]
            if b > 140 and (b - r) > 60 and (b - g) > 30:
                bp.append((r, g, b))
    bp.sort()
    return bp[len(bp) // 2]

def process(src, dst):
    img = Image.open(src).convert("RGB")

    white = (48, 753, 1156, 875)   # white search pill bbox (measured)
    blue  = (912, 755, 1155, 873)  # old blue AI pill bbox (measured)

    blue_col = median_blue(img)

    # new pill: shorter (white visible above/below) and shifted left (white on right)
    f = ImageFont.truetype(ARIAL_BD, 44 * S)
    tw = f.getlength("AI Assistant") / S
    new_right = 1146                 # ~10px white gap to the white pill edge (1156)
    new_top, new_bottom = 761, 867   # ~8px white gap above/below (753..875)
    new_left = int(round(new_right - tw -  2 * 48))

    # region covers old + new pill and the white pill's right edge
    rx0, ry0, rx1, ry1 = new_left - 40, white[1] - 6, white[2] + 8, white[3] + 6
    region = (rx0, ry0, rx1, ry1)

    crop = img.crop(region)
    big = crop.resize((crop.width * S, crop.height * S), Image.LANCZOS)
    d = ImageDraw.Draw(big)

    def sx(x): return (x - rx0) * S
    def sy(y): return (y - ry0) * S

    d.rounded_rectangle([sx(white[0]), sy(white[1]), sx(white[2]), sy(white[3])],
                        radius=(white[3] - white[1]) * S // 2, fill=(255, 255, 255))
    d.rounded_rectangle([sx(new_left), sy(new_top), sx(new_right), sy(new_bottom)],
                        radius=(new_bottom - new_top) * S // 2, fill=blue_col)
    d.text(((sx(new_left) + sx(new_right)) / 2, (sy(new_top) + sy(new_bottom)) / 2),
           "AI Assistant", font=f, fill=(255, 255, 255), anchor="mm")

    img.paste(big.resize(crop.size, Image.LANCZOS), region)
    img.save(dst, quality=92)
    print("saved", dst, "| new pill", (new_left, new_top, new_right, new_bottom),
          "| text w", round(tw, 1), "| blue", blue_col)

process(BASE + r"/corpid_logined_header_en.jpg", BASE + r"/corpid_logined_header_en.jpg")
process(BASE + r"/corpid_logined_header_2_en.jpg", BASE + r"/corpid_logined_header_2_en.jpg")
